[build]
  # Build command
  command = "cd frontend/src/icp-hub-frontend && npm install && npm run build"
  
  # Directory to publish (relative to root)
  publish = "frontend/src/icp-hub-frontend/dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--prefix frontend/src/icp-hub-frontend"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"