[build]
  # Build command to run
  command = "cd frontend && npm install && npm run build"
  # Publish directory (where the built site is located)
  publish = "frontend/dist"
  # Base directory for builds (optional, defaults to repository root)
  base = "."

[build.environment]
  # Set Node.js version
  NODE_VERSION = "22"
  # Set NPM version
  NPM_VERSION = "10"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"